/**
 * Operators, boats and trips.
 *
 * Commercial terms are seeded deliberately varied — three tiers, four
 * acquisition channels, one operator with insurance about to lapse and one
 * still pending approval — so that the ops queue, the trust badges and the
 * margin dashboard all have something real to show on a fresh install rather
 * than a uniformly healthy dataset that exercises none of the edge handling.
 */

export interface OperatorSeed {
  slug: string;
  name: string;
  type: "CHARTER_COMPANY" | "PRIVATE_OWNER";
  homePort: string;
  about: string;
  status: "PENDING" | "VERIFIED" | "SUSPENDED";
  licenceVerified: boolean;
  licenceRef: string | null;
  insuranceVerified: boolean;
  /** Days from seed time; negative is already expired. */
  insuranceExpiresInDays: number | null;
  safetyDeclaredDaysAgo: number | null;
  commercialTier: "STANDARD" | "PREFERRED" | "EXCLUSIVE";
  netRateDiscountPct: number;
  allotmentBerths: number;
  paymentTermsDays: number;
  responseTimeHours: number;
  ratingAvg: number;
  reviewCount: number;
}

export const OPERATORS: OperatorSeed[] = [
  {
    slug: "adriatic-blue",
    name: "Adriatic Blue Charter",
    type: "CHARTER_COMPANY",
    homePort: "ACI Marina Split",
    about:
      "Family-run base in Split operating a mixed fleet of monohulls and catamarans since 2009. Strong on first-timers: their handover briefing is the most thorough we have sat through anywhere in Croatia.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "HR-CH-4471",
    insuranceVerified: true,
    insuranceExpiresInDays: 240,
    safetyDeclaredDaysAgo: 70,
    commercialTier: "PREFERRED",
    netRateDiscountPct: 0.16,
    allotmentBerths: 24,
    paymentTermsDays: 21,
    responseTimeHours: 3,
    ratingAvg: 4.8,
    reviewCount: 64,
  },
  {
    slug: "dalmatia-sail-co",
    name: "Dalmatia Sail Co.",
    type: "CHARTER_COMPANY",
    homePort: "SCT Marina Trogir",
    about:
      "The largest fleet we work with in Croatia, based in Trogir and covering the Kornati and the southern islands. Our exclusive partner for the northern Dalmatian routes.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "HR-CH-2210",
    insuranceVerified: true,
    insuranceExpiresInDays: 310,
    safetyDeclaredDaysAgo: 45,
    commercialTier: "EXCLUSIVE",
    netRateDiscountPct: 0.23,
    allotmentBerths: 48,
    paymentTermsDays: 14,
    responseTimeHours: 2,
    ratingAvg: 4.6,
    reviewCount: 112,
  },
  {
    slug: "kvarner-yachting",
    name: "Kvarner Yachting",
    type: "CHARTER_COMPANY",
    homePort: "Marina Punat, Krk",
    about:
      "Northern Adriatic specialists out of Punat. Every skipper on their books has worked this coast for years, which on bora water is the qualification that matters.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "HR-CH-8802",
    insuranceVerified: true,
    // Deliberately inside the 30-day window: this seeds an EXPIRING_DOCUMENT
    // task and downgrades the public trust badge without anyone touching it.
    insuranceExpiresInDays: 19,
    safetyDeclaredDaysAgo: 120,
    commercialTier: "STANDARD",
    netRateDiscountPct: 0.1,
    allotmentBerths: 0,
    paymentTermsDays: 30,
    responseTimeHours: 9,
    ratingAvg: 4.5,
    reviewCount: 28,
  },
  {
    slug: "golfo-charter",
    name: "Golfo Charter Napoli",
    type: "CHARTER_COMPANY",
    homePort: "Marina d'Arechi, Salerno",
    about:
      "Salerno-based operator covering the Amalfi coast and the Pontine islands. They hold berth allocations on the Amalfi coast that are close to impossible to get independently.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "IT-NA-1183",
    insuranceVerified: true,
    insuranceExpiresInDays: 190,
    safetyDeclaredDaysAgo: 95,
    commercialTier: "PREFERRED",
    netRateDiscountPct: 0.15,
    allotmentBerths: 12,
    paymentTermsDays: 21,
    responseTimeHours: 5,
    ratingAvg: 4.4,
    reviewCount: 41,
  },
  {
    slug: "eolie-yacht",
    name: "Eolie Yacht",
    type: "CHARTER_COMPANY",
    homePort: "Marina di Portorosa",
    about:
      "Aeolian specialists based at Portorosa. Their skippers run the Stromboli night approach most weeks of the season and know exactly where to stand off it.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "IT-ME-0447",
    insuranceVerified: true,
    insuranceExpiresInDays: 275,
    safetyDeclaredDaysAgo: 30,
    commercialTier: "PREFERRED",
    netRateDiscountPct: 0.17,
    allotmentBerths: 16,
    paymentTermsDays: 21,
    responseTimeHours: 4,
    ratingAvg: 4.9,
    reviewCount: 53,
  },
  {
    slug: "smeralda-charter",
    name: "Smeralda Charter",
    type: "CHARTER_COMPANY",
    homePort: "Marina di Portisco",
    about:
      "Northern Sardinia operator with a modern fleet and, usefully, an in-house arrangement for La Maddalena park permits so crews are not doing that paperwork themselves.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "IT-OT-3390",
    insuranceVerified: true,
    insuranceExpiresInDays: 205,
    safetyDeclaredDaysAgo: 60,
    commercialTier: "PREFERRED",
    netRateDiscountPct: 0.14,
    allotmentBerths: 14,
    paymentTermsDays: 21,
    responseTimeHours: 6,
    ratingAvg: 4.7,
    reviewCount: 37,
  },
  {
    slug: "ibiza-blue-sailing",
    name: "Ibiza Blue Sailing",
    type: "CHARTER_COMPANY",
    homePort: "Marina Botafoch, Ibiza",
    about:
      "Our exclusive Balearics partner and the base most of the Crew departures run from. They hold a standing block of Formentera mooring reservations, which is the single hardest thing to obtain on this ground.",
    status: "VERIFIED",
    licenceVerified: true,
    licenceRef: "ES-IB-7729",
    insuranceVerified: true,
    insuranceExpiresInDays: 330,
    safetyDeclaredDaysAgo: 25,
    commercialTier: "EXCLUSIVE",
    netRateDiscountPct: 0.24,
    allotmentBerths: 60,
    paymentTermsDays: 14,
    responseTimeHours: 2,
    ratingAvg: 4.8,
    reviewCount: 96,
  },
  {
    slug: "marco-ferrari",
    name: "Marco Ferrari",
    type: "PRIVATE_OWNER",
    homePort: "Marina Corricella, Procida",
    about:
      "Private owner running his own boat out of Procida for part of the season. Applied through the site and is still working through verification.",
    // Pending: seeds an OPERATOR_APPROVAL task and keeps his boat out of search
    // until a human clears it.
    status: "PENDING",
    licenceVerified: false,
    licenceRef: null,
    insuranceVerified: false,
    insuranceExpiresInDays: null,
    safetyDeclaredDaysAgo: null,
    commercialTier: "STANDARD",
    netRateDiscountPct: 0.08,
    allotmentBerths: 0,
    paymentTermsDays: 30,
    responseTimeHours: 62,
    ratingAvg: 0,
    reviewCount: 0,
  },
];

export interface BoatSeed {
  slug: string;
  name: string;
  operatorSlug: string;
  type: "MONOHULL" | "CATAMARAN" | "GULET";
  model: string;
  lengthM: number;
  cabins: number;
  berths: number;
  heads: number;
  builtYear: number;
  refitYear: number | null;
  homePort: string;
  amenities: string[];
}

const COMMON = ["Bimini", "Cockpit table", "Chart plotter", "Bluetooth stereo"];
const PLUS = ["Bow thruster", "Electric winch", "Solar panels"];

export const BOATS: BoatSeed[] = [
  // Adriatic Blue — Split
  {
    slug: "maestral",
    name: "Maestral",
    operatorSlug: "adriatic-blue",
    type: "MONOHULL",
    model: "Bavaria Cruiser 46",
    lengthM: 14.27,
    cabins: 4,
    berths: 8,
    heads: 2,
    builtYear: 2019,
    refitYear: 2024,
    homePort: "ACI Marina Split",
    amenities: [...COMMON, ...PLUS, "Paddleboard"],
  },
  {
    slug: "burin",
    name: "Burin",
    operatorSlug: "adriatic-blue",
    type: "CATAMARAN",
    model: "Lagoon 42",
    lengthM: 12.8,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2021,
    refitYear: null,
    homePort: "ACI Marina Split",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning", "Watermaker"],
  },
  {
    slug: "levanat",
    name: "Levanat",
    operatorSlug: "adriatic-blue",
    type: "MONOHULL",
    model: "Elan Impression 40",
    lengthM: 12.25,
    cabins: 3,
    berths: 6,
    heads: 2,
    builtYear: 2018,
    refitYear: 2023,
    homePort: "ACI Marina Split",
    amenities: [...COMMON, "Bow thruster"],
  },
  // Dalmatia Sail Co — Trogir
  {
    slug: "kornat",
    name: "Kornat",
    operatorSlug: "dalmatia-sail-co",
    type: "MONOHULL",
    model: "Jeanneau Sun Odyssey 449",
    lengthM: 13.65,
    cabins: 4,
    berths: 8,
    heads: 2,
    builtYear: 2020,
    refitYear: null,
    homePort: "SCT Marina Trogir",
    amenities: [...COMMON, ...PLUS],
  },
  {
    slug: "zirje",
    name: "Žirje",
    operatorSlug: "dalmatia-sail-co",
    type: "MONOHULL",
    model: "Dufour 430",
    lengthM: 13.05,
    cabins: 3,
    berths: 6,
    heads: 2,
    builtYear: 2022,
    refitYear: null,
    homePort: "SCT Marina Trogir",
    amenities: [...COMMON, ...PLUS, "Air conditioning"],
  },
  {
    slug: "telascica",
    name: "Telašćica",
    operatorSlug: "dalmatia-sail-co",
    type: "CATAMARAN",
    model: "Bali 4.4",
    lengthM: 13.4,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2023,
    refitYear: null,
    homePort: "SCT Marina Trogir",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning", "Seabob"],
  },
  // Kvarner Yachting — Punat
  {
    slug: "bura",
    name: "Bura",
    operatorSlug: "kvarner-yachting",
    type: "MONOHULL",
    model: "Hanse 458",
    lengthM: 13.95,
    cabins: 4,
    berths: 8,
    heads: 2,
    builtYear: 2019,
    refitYear: 2024,
    homePort: "Marina Punat, Krk",
    amenities: [...COMMON, "Bow thruster", "Radar", "Storm jib"],
  },
  {
    slug: "susak",
    name: "Susak",
    operatorSlug: "kvarner-yachting",
    type: "MONOHULL",
    model: "Bavaria Cruiser 41",
    lengthM: 12.35,
    cabins: 3,
    berths: 6,
    heads: 2,
    builtYear: 2017,
    refitYear: 2023,
    homePort: "Marina Punat, Krk",
    amenities: [...COMMON, "Radar", "Storm jib"],
  },
  // Golfo Charter — Salerno
  {
    slug: "partenope",
    name: "Partenope",
    operatorSlug: "golfo-charter",
    type: "MONOHULL",
    model: "Beneteau Oceanis 46.1",
    lengthM: 14.6,
    cabins: 4,
    berths: 8,
    heads: 3,
    builtYear: 2021,
    refitYear: null,
    homePort: "Marina d'Arechi, Salerno",
    amenities: [...COMMON, ...PLUS, "Air conditioning"],
  },
  {
    slug: "ventotene",
    name: "Ventotene",
    operatorSlug: "golfo-charter",
    type: "CATAMARAN",
    model: "Fountaine Pajot Astréa 42",
    lengthM: 12.58,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2022,
    refitYear: null,
    homePort: "Marina d'Arechi, Salerno",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning"],
  },
  // Eolie Yacht — Portorosa
  {
    slug: "sciara",
    name: "Sciara",
    operatorSlug: "eolie-yacht",
    type: "MONOHULL",
    model: "Sun Odyssey 490",
    lengthM: 14.85,
    cabins: 4,
    berths: 8,
    heads: 4,
    builtYear: 2022,
    refitYear: null,
    homePort: "Marina di Portorosa",
    amenities: [...COMMON, ...PLUS, "Radar", "Air conditioning"],
  },
  {
    slug: "panarea",
    name: "Panarea",
    operatorSlug: "eolie-yacht",
    type: "CATAMARAN",
    model: "Lagoon 46",
    lengthM: 13.99,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2023,
    refitYear: null,
    homePort: "Marina di Portorosa",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning", "Watermaker"],
  },
  // Smeralda Charter — Portisco
  {
    slug: "budelli",
    name: "Budelli",
    operatorSlug: "smeralda-charter",
    type: "MONOHULL",
    model: "Dufour 470",
    lengthM: 14.35,
    cabins: 4,
    berths: 8,
    heads: 3,
    builtYear: 2023,
    refitYear: null,
    homePort: "Marina di Portisco",
    amenities: [...COMMON, ...PLUS, "Air conditioning", "Paddleboard"],
  },
  {
    slug: "spargi",
    name: "Spargi",
    operatorSlug: "smeralda-charter",
    type: "CATAMARAN",
    model: "Lagoon 40",
    lengthM: 11.74,
    cabins: 4,
    berths: 8,
    heads: 4,
    builtYear: 2021,
    refitYear: null,
    homePort: "Marina di Portisco",
    amenities: [...COMMON, ...PLUS, "Generator", "Snorkelling kit"],
  },
  // Ibiza Blue Sailing
  {
    slug: "vedra",
    name: "Vedrà",
    operatorSlug: "ibiza-blue-sailing",
    type: "CATAMARAN",
    model: "Lagoon 450F",
    lengthM: 13.96,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2020,
    refitYear: 2024,
    homePort: "Marina Botafoch, Ibiza",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning", "Paddleboard", "Seabob"],
  },
  {
    slug: "espalmador",
    name: "Espalmador",
    operatorSlug: "ibiza-blue-sailing",
    type: "MONOHULL",
    model: "Oceanis 51.1",
    lengthM: 15.94,
    cabins: 5,
    berths: 10,
    heads: 3,
    builtYear: 2022,
    refitYear: null,
    homePort: "Marina Botafoch, Ibiza",
    amenities: [...COMMON, ...PLUS, "Air conditioning", "Paddleboard"],
  },
  {
    slug: "illetes",
    name: "Illetes",
    operatorSlug: "ibiza-blue-sailing",
    type: "CATAMARAN",
    model: "Bali 4.2",
    lengthM: 12.85,
    cabins: 4,
    berths: 10,
    heads: 4,
    builtYear: 2023,
    refitYear: null,
    homePort: "Marina Botafoch, Ibiza",
    amenities: [...COMMON, ...PLUS, "Generator", "Air conditioning", "Snorkelling kit"],
  },
  // Marco Ferrari — pending
  {
    slug: "corricella",
    name: "Corricella",
    operatorSlug: "marco-ferrari",
    type: "MONOHULL",
    model: "Grand Soleil 43",
    lengthM: 13.2,
    cabins: 3,
    berths: 6,
    heads: 2,
    builtYear: 2015,
    refitYear: 2022,
    homePort: "Marina Corricella, Procida",
    amenities: [...COMMON, "Bow thruster"],
  },
];

export interface TripSeed {
  slug: string;
  name: string;
  summary: string;
  boatSlug: string;
  destinationSlug: string;
  itineraryKey: string;
  format: "WHOLE_BOAT" | "CABIN_CHARTER" | "FLOTILLA";
  skipper: "SKIPPERED" | "BAREBOAT";
  skillLevel: "FIRST_TIMER" | "COMPETENT_CREW" | "SKIPPER";
  durationDays: number;
  startPort: string;
  endPort: string;
  isCrewTrip: boolean;
  minAge: number | null;
  maxAge: number | null;
  /** Base weekly net rate in EUR before tier discount and seasonality. */
  baseNetRateEur: number;
  /** Which months this trip runs, 1-12. */
  months: number[];
}

export const TRIPS: TripSeed[] = [
  // ------------------------------------------------------------- Dalmatia
  {
    slug: "dalmatia-first-week-skippered",
    name: "Dalmatia: the first sailing week",
    summary:
      "Split, Brač, Hvar and Vis with a skipper aboard. The week we send people on when they have never sailed and want to find out whether they like it.",
    boatSlug: "maestral",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Split",
    endPort: "Split",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 3600,
    months: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "dalmatia-catamaran-family",
    name: "Dalmatia by catamaran",
    summary:
      "The same island loop on a Lagoon 42, which is the right answer for families and for anyone who would rather not sleep at an angle.",
    boatSlug: "burin",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Split",
    endPort: "Split",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 5200,
    months: [5, 6, 7, 8, 9],
  },
  {
    slug: "dalmatia-bareboat",
    name: "Dalmatia bareboat week",
    summary:
      "The island loop on your own, for crews who hold the licence and want the boat to themselves. Full route briefing and our readiness programme included.",
    boatSlug: "levanat",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-classic",
    format: "WHOLE_BOAT",
    skipper: "BAREBOAT",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Split",
    endPort: "Split",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 2700,
    months: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "hvar-crew-week",
    name: "Crew: Hvar and the Pakleni",
    summary:
      "Cabin charter for solo travellers and small groups in their twenties. Split, Hvar, Vis and Palmižana, with the boat as the base for the evenings.",
    boatSlug: "kornat",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-classic",
    format: "CABIN_CHARTER",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Split",
    endPort: "Split",
    isCrewTrip: true,
    minAge: 21,
    maxAge: 35,
    baseNetRateEur: 3900,
    months: [6, 7, 8, 9],
  },
  {
    slug: "kornati-national-park",
    name: "The Kornati and Telašćica",
    summary:
      "North from Trogir into the bare limestone of the national park — eighty islands, almost nobody, and the quietest week we sell in Croatia.",
    boatSlug: "zirje",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-kornati",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Trogir",
    endPort: "Trogir",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 3300,
    months: [5, 6, 7, 8, 9],
  },
  {
    slug: "kornati-catamaran",
    name: "Kornati by catamaran",
    summary:
      "The park loop on a Bali 4.4, with the space and the shade to make the middle of August genuinely comfortable.",
    boatSlug: "telascica",
    destinationSlug: "dalmatia",
    itineraryKey: "dalmatia-kornati",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Trogir",
    endPort: "Trogir",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 5600,
    months: [6, 7, 8, 9],
  },
  // -------------------------------------------------------------- Kvarner
  {
    slug: "kvarner-islands-week",
    name: "Kvarner: Rab, Lošinj and Istria",
    summary:
      "The quieter half of Croatia, skippered by people who have worked bora water for years. Better sailing than Dalmatia and a third of the boats.",
    boatSlug: "bura",
    destinationSlug: "kvarner",
    itineraryKey: "kvarner-islands",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Punat, Krk",
    endPort: "Pula",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 3400,
    months: [6, 7, 8, 9],
  },
  {
    slug: "kvarner-shoulder-season",
    name: "Kvarner in the shoulder season",
    summary:
      "May and October on the northern Adriatic: the best sailing of the year, empty harbours, and a skipper aboard because the bora risk is real.",
    boatSlug: "susak",
    destinationSlug: "kvarner",
    itineraryKey: "kvarner-islands",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Punat, Krk",
    endPort: "Pula",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 2400,
    months: [5, 10],
  },
  // ------------------------------------------------------- Amalfi/Pontine
  {
    slug: "amalfi-capri-week",
    name: "Amalfi, Capri and the Gulf",
    summary:
      "Salerno, Amalfi, Capri, Ischia and Procida, skippered, with the marina berths already reserved — which on this coast is most of the battle.",
    boatSlug: "partenope",
    destinationSlug: "amalfi-pontine",
    itineraryKey: "amalfi-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Marina d'Arechi, Salerno",
    endPort: "Marina d'Arechi, Salerno",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 5400,
    months: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "amalfi-catamaran",
    name: "The Gulf of Naples by catamaran",
    summary:
      "The same coast with the shade and deck space a hot August week on the Tyrrhenian genuinely needs.",
    boatSlug: "ventotene",
    destinationSlug: "amalfi-pontine",
    itineraryKey: "amalfi-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Marina d'Arechi, Salerno",
    endPort: "Marina d'Arechi, Salerno",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 6800,
    months: [6, 7, 8, 9],
  },
  // -------------------------------------------------------------- Aeolians
  {
    slug: "aeolian-volcano-week",
    name: "The Aeolians and the Stromboli night",
    summary:
      "Seven volcanic islands in a week, built around standing off the Sciara del Fuoco after dark while Stromboli erupts. The trip people talk about for years.",
    boatSlug: "sciara",
    destinationSlug: "aeolian-islands",
    itineraryKey: "aeolian-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Milazzo",
    endPort: "Milazzo",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 4700,
    months: [6, 7, 8, 9],
  },
  {
    slug: "aeolian-catamaran",
    name: "Aeolians by catamaran",
    summary:
      "The volcano loop on a Lagoon 46, with the stability that makes the night watch off Stromboli comfortable rather than endured.",
    boatSlug: "panarea",
    destinationSlug: "aeolian-islands",
    itineraryKey: "aeolian-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Milazzo",
    endPort: "Milazzo",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 6400,
    months: [6, 7, 8, 9],
  },
  // ---------------------------------------------------------- La Maddalena
  {
    slug: "maddalena-archipelago",
    name: "La Maddalena and the Strait",
    summary:
      "Granite, turquoise water and the best anchorages in the Tyrrhenian, with a run across to Bonifacio if the mistral allows. Park permits handled for you.",
    boatSlug: "budelli",
    destinationSlug: "la-maddalena",
    itineraryKey: "maddalena-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "COMPETENT_CREW",
    durationDays: 7,
    startPort: "Portisco",
    endPort: "Portisco",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 5100,
    months: [5, 6, 7, 8, 9],
  },
  {
    slug: "maddalena-bareboat",
    name: "La Maddalena bareboat",
    summary:
      "The archipelago on your own, on a Lagoon 40. For crews who hold the licence and are comfortable planning a week around the mistral.",
    boatSlug: "spargi",
    destinationSlug: "la-maddalena",
    itineraryKey: "maddalena-classic",
    format: "WHOLE_BOAT",
    skipper: "BAREBOAT",
    skillLevel: "SKIPPER",
    durationDays: 7,
    startPort: "Portisco",
    endPort: "Portisco",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 4300,
    months: [5, 6, 7, 8, 9],
  },
  // ------------------------------------------------------------- Balearics
  {
    slug: "ibiza-formentera-week",
    name: "Ibiza and Formentera",
    summary:
      "Illetes, Espalmador, Es Vedrà and the west-coast sunsets, with the Formentera mooring buoys already reserved — the thing that is close to impossible to arrange yourself.",
    boatSlug: "vedra",
    destinationSlug: "ibiza-formentera",
    itineraryKey: "ibiza-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Marina Botafoch, Ibiza",
    endPort: "Marina Botafoch, Ibiza",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 6100,
    months: [5, 6, 7, 8, 9, 10],
  },
  {
    slug: "ibiza-crew-week",
    name: "Crew: Ibiza and Formentera",
    summary:
      "Six days, a cabin each, and a boat full of people in their twenties who did not know each other on Monday. Solo travellers welcome — most of the boat books that way.",
    boatSlug: "espalmador",
    destinationSlug: "ibiza-formentera",
    itineraryKey: "ibiza-crew",
    format: "CABIN_CHARTER",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 6,
    startPort: "Marina Botafoch, Ibiza",
    endPort: "Marina Botafoch, Ibiza",
    isCrewTrip: true,
    minAge: 21,
    maxAge: 35,
    baseNetRateEur: 5400,
    months: [6, 7, 8, 9],
  },
  // Marco Ferrari's boat. His operator record is still PENDING, so this trip
  // exists in the database and is correctly invisible in search — the seeded
  // proof that `findTrips` gates on verification rather than trusting a flag
  // somebody remembered to set.
  {
    slug: "procida-owner-week",
    name: "Procida and the Gulf, with the owner",
    summary:
      "A week on the Gulf of Naples aboard Marco's own boat, sailed by the man who has kept it in Corricella for a decade.",
    boatSlug: "corricella",
    destinationSlug: "amalfi-pontine",
    itineraryKey: "amalfi-classic",
    format: "WHOLE_BOAT",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 7,
    startPort: "Marina Corricella, Procida",
    endPort: "Marina Corricella, Procida",
    isCrewTrip: false,
    minAge: null,
    maxAge: null,
    baseNetRateEur: 3900,
    months: [6, 7, 8, 9],
  },
  {
    slug: "ibiza-crew-flotilla",
    name: "Crew: the Formentera flotilla",
    summary:
      "Three boats sailing the same route together, with a lead skipper and a shared plan each evening. The most sociable thing we run.",
    boatSlug: "illetes",
    destinationSlug: "ibiza-formentera",
    itineraryKey: "ibiza-crew",
    format: "FLOTILLA",
    skipper: "SKIPPERED",
    skillLevel: "FIRST_TIMER",
    durationDays: 6,
    startPort: "Marina Botafoch, Ibiza",
    endPort: "Marina Botafoch, Ibiza",
    isCrewTrip: true,
    minAge: 21,
    maxAge: 38,
    baseNetRateEur: 5000,
    months: [6, 7, 8],
  },
];
